let mainTags = {
  //International
  'Western Europe': ['International'],
  International: ['International'],
  'Central and Eastern Europe': ['International'],
  Asia: ['International'],
  Africa: ['International'],
  'Mediterranean & Middle East': ['International'],
  Americas: ['International'],
  'South and Central Asia': ['International'],

  //Country
  India: ['Country'],
  Netherlands: ['country'],

  //Business
  Sensex: ['Business'],
  Business: ['Business'],
  Nifty: ['Business'],
  Crypto: ['Business'],
  Dollar: ['Business'],
  Editorial: ['Business'],

  //Sports
  Cricket: ['Sports'],
  Football: ['Sports'],
  Baseball: ['Sports'],
  Hockey: ['Sports'],
  T20: ['Sports'],
  Test: ['Sports'],
  FIFA: ['Sports'],
  F1: ['Sports'],
  Golf: ['Sports'],
  Sport: ['Sports'],
  Tennis: ['Sports'],
  'Other Sports': ['Sports'],

  //National (India)
  National: ['National'],
  'Tamil Nadu': ['National'],
  Kerala: ['National'],
  'Other States': ['National'],
  Karnataka: ['National'],
  Telangana: ['National'],
  'Andhra Pradesh': ['National'],
  Odisha: ['National'],
  'West Bengal': ['National'],
  Bihar: ['National'],
  Gujarat: ['National'],
  Maharastra: ['National'],
  UttarPradesh: ['National'],
  'Arunachal Pradesh': ['National'],
  Assam: ['National'],
  Chhattisgarh: ['National'],
  Goa: ['National'],
  Haryana: ['National'],
  'Himachal Pradesh': ['National'],
  Jharkhand: ['National'],
  'Madhya Pradesh': ['National'],
  Manipur: ['National'],
  Meghalaya: ['National'],
  Mizoram: ['National'],
  Nagaland: ['National'],
  Punjab: ['National'],
  Rajasthan: ['National'],
  Sikkim: ['National'],
  Tripura: ['National'],
  Uttarkhand: ['National'],

  //Cities(India) & union territory
  Bengaluru: ['Cities'],
  Chennai: ['Cities'],
  Kolkata: ['Cities'],
  Thiruvananthapuram: ['Cities'],
  Delhi: ['Cities'],
  Visakhapatnam: ['cities'],
  Puducherry: ['Cities', 'Union Territory'],
  Mumbai: ['Cities'],
  Coimbatore: ['Cities'],
  Kochi: ['cities'],
  Ahmedabad: ['National'],
  Surat: ['National'],
  Pune: ['National'],
  Jaipur: ['National'],
  Lucknow: ['National'],
  Kanpur: ['National'],
  Nagpur: ['National'],
  Indore: ['National'],
  Thane: ['National'],
  Bhopal: ['National'],
  Patna: ['National'],
  Vadodra: ['National'],
  Ghaziabad: ['National'],
  Ludhiana: ['National'],
  Agra: ['National'],
  Nasik: ['National'],
  Faridabad: ['National'],
  Meerut: ['National'],
  Amritsar: ['National'],
  Ranchi: ['National'],
  Vijayawada: ['National'],
  TiruchiraPalli: ['National'],
  'Andaman and Nicobar Islands': ['Union Territory'],
  Chandigarh: ['Union Territory'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Union Territory'],
  'Jammu and Kashmir': ['Union Territory'],
  Ladakh: ['Union Territory'],
  Lakshadweep: ['Union Territory'],

  //Defense
  Military: ['Defense'],
  'Royal Navy': ['Defense'],

  //Entertainment & Games
  Movies: ['Entertainment'],
  Podcast: ['Entertainment'],
  Podcasts: ['Entertainment'],
  'Television & radio': ['Entertainment'],
  Television: ['Entertainment'],
  Audio: ['Entertainment'],
  Video: ['Entertainment'],
  Comic: ['Entertainment'],
  PS5: ['Entertainment', 'Games'],
  'PlayStation 5': ['Entertainment', 'Games'],
  'Video Games': ['Entertainment', 'Games'],
  Comedy: ['Entertainment'],
  Actor: ['Entertainment'],
  Actress: ['Entertainment'],
  Comedian: ['Entertainment'],
  Theatre: ['Entertainment'],
  'Digital media': ['Entertainment'],
  Media: ['Entertainment'],
  'Alfred Hitchcock': ['Entertainment'],
  Thrillers: ['Entertainment'],
  Games: ['Games'],
  Film: ['Entertainment'],
  'Nintendo Switch': ['Entertainment', 'Games'],
  'Mobile games': ['Entertainment', 'Games'],
  'Action games': ['Entertainment', 'Games'],
  'Amazon Prime Video': ['Entertainment'],
  Netflix: ['Entertainment'],
  'Disney+': ['Entertainment'],
  Hotstar: ['Entertainment'],
  Smartphones: ['Entertainment'],
  '3D printing': ['Technology'],
  PlayStation: ['Entertainment', 'Games'],


  //Education
  Education: ['Education'],

  //Technology & Gadgets
  Podcasts: ['Technology'],
  Podcasting: ['Technology'],
  Gadgets: ['Technology', 'Gadgets'],
  IT: ['Technology'],
  Technology: ['Technology'],
  Computer: ['Technology'],
  AI: ['Technology'],
  Google: ['Technology'],
  Internet: ['Technology'],
  Apple: ['Technology'],
  Alexa: ['Technology', 'Gadgets'],
  Samsung: ['Technology'],
  Mobile: ['Technology', 'Gadgets'],
  Laptop: ['Technology', 'Gadgets'],
  Tablet: ['Technology', 'Gadgets'],
  PC: ['Technology'],
  Tech: ['Technology'],
  Microsoft: ['Technology'],
  Flipkart: ['Technology'],
  Amazon: ['Technology'],
  iPad: ['Technology', 'Gadgets'],
  'Tablet computers': ['Technology', 'Gadgets'],
  Headphones: ['Technology', 'Gadgets'],
  Android: ['Technology', 'Gadgets'],
  iOS: ['Technology', 'Gadgets'],
  Windows: ['Technology'],
  Phone: ['Technology', 'Gadgets'],
  'Smart Phone': ['Technology', 'Gadgets'],
  Speaker: ['Technology', 'Gadgets'],
  Bluetooth: ['Technology', 'Gadgets'],
  Wifi: ['Technology'],
  SpaceX: ['Technology'],
  Internet: ['Technology'],
  'Face Recognition': ['Technology'],
  'Facial Recognition': ['Technology'],
  Alexa: ['Technology'],
  Siri: ['Technology'],
  Facebook: ['Technology'],
  Instagram: ['Technology'],
  TikTok: ['Technology'],
  Space: ['Technology'],
  'Richard Branson': ['Technology'],
  'Elon Musk': ['Technology'],
  Science: ['Technology'],
  'Jeff Bezos': ['Technology'],
  Technology: ['Technology'],
  'E-commerce': ['Technology'],
  'Social networking': ['Technology'],
  Broadband: ['Technology'],
  'Social media': ['Technology'],
  Apps: ['Technology'],
  Twitch: ['Technolgy', 'Games'],
  "Assassin's Creed": ['Games'],
  'Xbox series S/X': ['Games'],
  Xbox: ['Technology', 'Games'],
  Stage: ['Entertainment'],
  'National Theatre': ['Entertainment'],
  Livestreaming: ['Games'],
  'Apple TV': ['Technology'],
  DeepMind: ['Technology'],
  'Artificial intelligence (AI)': ['Technology'],
  'Wearable technology': ['Technology'],
  'Google Home': ['Technology'],
  'Amazon Alexa': ['Technology'],
  Skype: ['Technology'],
  Computing: ['Technology'],
  Laptops: ['Technology'],
  'Google Assistant': ['Technology'],
  'Mobile phones': ['Technology'],
  'Smart speakers': ['Technology'],
  'TV streaming': ['Technology'],
  Sky: ['Technology'],
  'Virgin Media': ['Technology'],

  //Lifestyle & Food
  Running: ['LifeStyle'],
  Family: ['LifeStyle'],
  Cycling: ['LifeStyle'],
  Hobbies: ['LifeStyle'],
  Fashion: ['LifeStyle'],
  Culture: ['Lifestyle'],
  Food: ['Food'],
  'Life and style': ['Lifestyle'],
  Coffee: ['Food'],
  'Ice-cream and sorbet': ['Food'],
  'Ice-cream': ['Food'],
  Pasta: ['Food'],
  Bread: ['Food'],
  Eggs: ['Food'],
  Dating: ['LifeStyle'],
  Tinder: ['LifeStyle', 'Technology'],
  Sex: ['LifeStyle'],
  'Young people': ['Lifestyle'],
  Fitness: ['LifeStyle'],

  //Economy , Currency, Industry
  Bank: ['Economy'],
  Economy: ['Economy'],
  Crypto: ['Economy'],
  Currency: ['Economy', 'Currency'],
  Dollar: ['currency'],
  G7: ['Economy'],
  Tax: ['Economy'],
  'Tax Avoidance': ['Economy'],
  Corporate: ['Economy'],
  Government: ['Economy'],
  Oil: ['Economy'],
  Gas: ['Economy'],
  Companies: ['Economy'],
  'Corporate governance': ['Economy'],
  Bitcoin: ['Currency'],
  Cryptocurrencies: ['Economy', 'Currency'],
  Banking: ['Economy'],
  'Global economy': ['Economy'],
  Economics: ['Economy'],
  BT: ['Economy'],
  "Telecommunications industr'": ['Industry'],
  Morrisons: ['Economy'],
  'Executive pay and bonuses': ['Economy', 'Industry'],
  'Retail industry': ['Industry'],
  Supermarkets: ['Industry'],
  'Public services policy': ['Economy'],
  Society: ['Economy'],
  'Housing market': ['Economy'],
  'Green building': ['Economy'],
  'Telecommunications industry': ['Economy', 'Industry'],
  'Television industry': ['Economy', 'Industry'],

  //Science
  Bluto: ['Science'],
  Sun: ['Science'],
  Earth: ['Science'],
  Physics: ['Science'],
  Chemistry: ['Science'],

  //Automotive
  Car: ['Automotive'],
  Tesla: ['Automotive'],
  Auto: ['Automotive'],
  Taxi: ['Automotive'],
  Flight: ['Automotive'],
  Aeroplane: ['Automotive'],
  Truck: ['Automotive'],
  Fuel: ['Automotive'],
  Petrol: ['Automotive'],
  Diesel: ['Automotive'],
  Electric: ['Automotive'],
  eBike: ['Automotive'],
  Bike: ['Automotive'],
  Cycle: ['Automotive'],

  //Information
  'US news': ['Information'],
  'World news': ['Information'],
  'Australia news': ['Information'],
  'UK news': ['Information'],

  //Politics
  Politics: ['Politics'],
  'Rishi Sunak': ['Politics'],
  'US politics': ['Politics'],

  //Health
  Vertigo: ['Health'],
  Coronavirus: ['Health'],
  Vaccine: ['HEalth'],
  Immune: ['Health'],
  immunisation: ['Health'],
  Immunity: ['Health'],
  'Vaccines and immunisation': ['Health'],
  Health: ['Health'],
  'Infectious diseases': ['Health'],
  Disease: ['Health'],
  Diseases: ['Health'],
  'Health policy': ['Health'],

  //null
  null: ['Category'],
};

module.exports = mainTags;
